title: "Miroslav Sykora — Notes & Projects"
description: "Optimization, mathematics, and machine learning notes; personal reflections; and projects."
url: "" #"https://mirasyko.github.io" # set later, e.g. https://yourname.github.io
baseurl: "" #"/Mirasyko.github.io" # e.g. /site if using a subpath


markdown: kramdown
kramdown:
input: GFM
math_engine: mathjax
hard_wrap: false
syntax_highlighter: rouge


collections:
  academic:
    output: true
    permalink: /academic/:name/
  personal:
    output: true
    permalink: /personal/:name/
  projects:
    output: true
    permalink: /projects/:name/


permalink: pretty

# Build settings
plugins:
- jekyll-feed
- jekyll-sitemap